from django.urls import path
from . import views

urlpatterns = [
    path('adminproductlist/',views.productlist,name="productlist"),
    path('adproductedit/<int:id>',views.productedit,name="productedit"),
    path('adproductadd/',views.productadd,name="productadd"),
    path('adproductview/<int:id>',views.productview,name="productview"),
    path('adshowvariant/<int:id>',views.variantview,name="variantview"),
    path('addvariant/<int:id>',views.addvariant,name="addvariant"),
    path('addvariantsize/<int:id>',views.addvariantsize,name="addvariantsize"),
    path('variantsizedit/<int:id>',views.variantsizedit,name="variantsizedit"),
    path('variantcolouredit/<int:id>',views.Variantcolouredit,name="variantcolouredit"),
    path('imageedit/<int:id>/<int:var_id>',views.imageedit,name="imageedit"),
    path('categoryview/',views.categoryview,name="categoryview"),
    path('categoryedit/<int:id>',views.categoryedit,name="categoryedit"),
    path('categoryadd/',views.categoryadd,name="categoryadd"),
    path('brandview/',views.brand_list,name="brandview"),
    path('brandedit/<int:id>',views.brandedit,name="brandedit"),
    path('brandadd/',views.brandadd,name="brandadd"),
    path('admindashboard/',views.dashboard,name="dashboard"),
    path('login/',views.admin_login,name="admin-login"),
    path('error',views.error_view,name='error'),
    path('adminlogout/',views.adminlogout,name='adminlogout'),
    path('orderlist/',views.Order_list,name="orderlist"),
    path('orderview<int:id>/',views.Order_View,name="orderview"),
    path('update-order-status', views.update_order_status, name='update_order_status'),
    path('update-refund-status', views.update_refund_status, name='update_refund_status'),
    path('user_details/', views.User_details, name='userdetails'),
    path('adproductoffer/', views.All_Offers, name='All_Offers'),
    path('Add_productoffer/', views.AddProductoffer, name='AddProductoffer'),
    path("editproductOffer/<int:id>", views.edit_productoffer, name='editproductOffer'),
    path("editbrandOffer/<int:id>", views.edit_brandoffer, name='editbrandOffer'),
    path('Add_brandoffer/', views.AddBrandoffer, name='AddBrandoffer'),
    path('delete_brandoffer/<int:id>', views.delete_Brand_Offer,name='delete_brandoffer'),
    path('delete_productoffer/<int:id>', views.delete_Product_Offer,name='delete_productoffer'),
    path('salesreport/',views.Sales_Report,name="salesreport"),
    path("Editcoupon/<int:id>", views.EditCoupon, name='Editcoupon'),
    path('AddCoupon/', views.AddCoupon, name='AddCoupon'),
    path('All_Coupons/', views.All_Coupons, name='All_Coupons'),
    path('deleteCoupon/<int:id>', views.delete_Coupon,name='deleteCoupon'),

]

