# Generated by Django 5.1.2 on 2024-11-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cart_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('PAYPAL', 'PayPal'), ('CARD', 'Credit/Debit Card'), ('UPI', 'UPI Payment')], default='COD', max_length=100),
        ),
    ]
