# Generated by Django 5.0.6 on 2024-11-10 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_variant_size_alter_category_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('in_review', 'In review')], default='in_review', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('in_review', 'In review')], default='in_review', max_length=50),
        ),
        migrations.AlterField(
            model_name='variantimages',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.colour'),
        ),
    ]
