# Generated by Django 5.0.6 on 2024-11-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_variant_size_alter_category_category_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='size',
            field=models.CharField(choices=[('xxl', 'xxl'), ('xl', 'xl'), ('lg', 'lg'), ('md', 'md'), ('sm', 'sm'), ('xs', 'xs')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='variantsize',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('in_review', 'In review'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=50),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
