# Generated by Django 5.1.2 on 2024-11-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orderitems_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
    ]
