# Generated by Django 5.1.2 on 2024-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_orderitems_status_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('out for Delivery', 'Out for Delivery')], default='processing', max_length=20),
        ),
    ]
