# Generated by Django 5.1.2 on 2024-11-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandoffer',
            old_name='product',
            new_name='brand',
        ),
    ]
