# Generated by Django 5.1.2 on 2024-12-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_rename_product_brandoffer_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='usage_limit',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_code', to='user.coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Enter the discount percentage (e.g., 10.00 for 10%).', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
    ]
