# Generated by Django 5.1.2 on 2024-12-07 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='cart_order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('razorpay', 'Razorpay'), ('wallet', 'wallet')], default='COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='return_status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product')),
            ],
            options={
                'verbose_name_plural': 'product reviews',
            },
        ),
    ]
