# Generated by Django 5.1.2 on 2024-12-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_review_user_alter_review_product_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
