# Generated by Django 5.1.2 on 2024-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_cart_order_shipping_address_cart_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cancel_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Not Cancelled', 'Not Cancelled')], default='Not Cancelled', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='return_status',
            field=models.CharField(choices=[('processing', 'processing'), ('Returned', 'Returned'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=20),
        ),
    ]
