# Generated by Django 5.1.2 on 2024-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_orderitems_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
