# Generated by Django 5.1.2 on 2024-12-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_orderitems_refund_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_order',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('out for Delivery', 'Out for Delivery'), ('Returned', 'Returned')], default='processing', max_length=20),
        ),
    ]
