# Generated by Django 5.1.2 on 2024-12-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_cart_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='colour',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
