# Generated by Django 5.1.2 on 2024-12-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_couponusage_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
    ]
