# Generated by Django 5.1.2 on 2024-12-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_order',
            name='user',
        ),
    ]
