# Generated by Django 5.1.2 on 2024-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_remove_cart_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_order',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
