from django.urls import path
from . import views

urlpatterns = [
    path('',views.create,name="home"),
    path('contact/',views.contact,name="contact"),
    path('blog/',views.blog,name="blog"),
    path('cart/',views.cart,name="cart"),
    path('wishlist/',views.wishlist,name="wishlist"),
    path('shop/',views.shop,name="shop"),
    path('product/<int:id>',views.product,name="product_detail"),
    path('get-variant-images/<id>/',views.get_variant_images,name="get_variant_images"),
    path('get-variant-sizes/<id>/',views.get_variant_sizes,name="get_variant_sizes"),
    path('filter-data',views.filter_data,name="filter_data"),
    path('add-tocart',views.add_to_cart,name="add_to_cart"),
    path('delete-tocart',views.delete_cart_item,name="delete-tocart"),
    path('update-tocart',views.update_cart_item,name="update-tocart"),
    path('myaccount/',views.Account,name="account"),
    path('editprofile/<int:id>/',views.Editprofile,name="editprofile"),
    path('order/',views.Order_details,name="order"),
    path('orderitems/<int:id>/', views.Order_items, name='orderitems'),
    path('address/',views.Address,name="address"),
    path('checkout/',views.Checkout,name="checkout"),
    path('addaddress/',views.Addaddress,name="addaddress"),
    path('editaddress/<int:id>/',views.Editaddress,name="editaddress"),
    path('deleteaddress/<int:id>/',views.Delete_address,name="deleteaddress"),
    path('order_success/',views.Order_success,name="order_success"),
    path('verify-payment/', views.verify_payment, name='verify_payment'),
    path('orderview/<int:order_id>/', views.Orderitem_view, name='order_view'),
    path('invoice_download/<int:id>/', views.Invoice_Download, name='invoice_download'),
    path('return-item/<int:item_id>/', views.return_item, name='return_item'),
    path('cancel-item/<int:item_id>/', views.cancel_item, name='cancel_item'),
    path('return-confirmation', views.return_confirmation, name='return_confirmation'),
    path('cancel_order/<int:id>/', views.Cancel_Order, name='cancel_order'),
    path('Return_order/<int:id>/', views.Return_Order, name='Return_order'),
    path('Retry/<int:id>/', views.Retry, name='Retry'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('remove-coupon/', views.removecoupon, name='removecoupon'),
    path('add-towishlist',views.add_to_wishlist,name="add_to_wishlist"),
    path('delete-towishlist',views.delete_wishlist_item,name="delete-towishlist"),
    path('mywallet/', views.My_wallet, name='mywallet'),
    path('ajax-add-review/<int:id>/', views.ajax_add_review, name='ajax_add_review'),
    path('search_view',views.search_view,name="search_view"),

]