# Generated by Django 5.0.6 on 2024-10-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phoneno',
        ),
    ]
