# Generated by Django 5.0.6 on 2024-10-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_remove_user_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
