# Generated by Django 5.0.6 on 2024-10-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneno',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
